In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("Churn_Modelling.csv")

In [3]:
x = data.iloc[:,3:13].values
y = data.iloc[:,4].values

In [4]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
# Encoding categorical data

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
a = LabelEncoder()
x[:,1] = a.fit_transform(x[:,1])

In [7]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
b = LabelEncoder()
x[:,2] = b.fit_transform(x[:,2])

In [9]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
x.dtype

dtype('O')

In [11]:
X = pd.DataFrame(x)

In [12]:
X.head()

0  1  2   3  4          5  6  7  8          9
0  619  0  0  42  2        0.0  1  1  1  101348.88
1  608  2  0  41  1   83807.86  1  0  1  112542.58
2  502  0  0  42  8   159660.8  3  1  0  113931.57
3  699  0  0  39  1        0.0  2  0  0   93826.63
4  850  2  0  43  2  125510.82  1  1  1    79084.1

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough')

In [15]:
x = ct.fit_transform(x)

In [16]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [17]:
x = x[:,1:]

In [18]:
X = pd.DataFrame(x)

In [19]:
X.head()

0    1    2  3   4  5          6  7  8  9          10
0  0.0  0.0  619  0  42  2        0.0  1  1  1  101348.88
1  0.0  1.0  608  0  41  1   83807.86  1  0  1  112542.58
2  0.0  0.0  502  0  42  8   159660.8  3  1  0  113931.57
3  0.0  0.0  699  0  39  1        0.0  2  0  0   93826.63
4  0.0  1.0  850  0  43  2  125510.82  1  1  1    79084.1

In [20]:
x.shape

(10000, 11)

In [21]:
y.shape

(10000,)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state =0)

In [23]:
from sklearn.preprocessing import StandardScaler  # Feature Scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [24]:
# Making of ANN model

In [25]:
import keras

In [26]:
from keras.models import Sequential # to initialize our neural network
from keras.layers import Dense  # used to create layers in our ANN

In [65]:
classifier = Sequential() # Initialising the ANN

In [28]:
# Since the number of nodes in the input layer is 11(number of independent variables) and output layer is 1 it implies 11+1/2 =6 (hidden layers)

In [29]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(6, kernel_initializer='glorot_uniform', activation ='relu', input_dim = 11)) 

In [30]:
# Adding the second hidden layer
classifier.add(Dense(6, kernel_initializer='glorot_uniform', activation ='relu')) 

In [31]:
# Adding the output layer
# for binary outcome there is only one node in the output layer
classifier.add(Dense(1, kernel_initializer='glorot_uniform', activation ='sigmoid', input_dim = 11)) 

In [40]:
# Compiling the ANN
classifier.compile(optimizer ='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [42]:
# fitting the ANN to the training set
classifier.fit(x_train,y_train,epochs =10)

Epoch 1/10


UnimplementedError: Graph execution error:

Detected at node 'binary_crossentropy/Cast' defined at (most recent call last):
    File "C:\Users\ril\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\ril\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "C:\Users\ril\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
      self.io_loop.start()
    File "C:\Users\ril\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\ril\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "C:\Users\ril\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "C:\Users\ril\anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
      await self.process_one()
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
      await dispatch(*args)
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 367, in dispatch_shell
      await result
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 662, in execute_request
      reply_content = await reply_content
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\Users\ril\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\ril\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2863, in run_cell
      result = self._run_cell(
    File "C:\Users\ril\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in _run_cell
      return runner(coro)
    File "C:\Users\ril\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\ril\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3106, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\ril\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3309, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\ril\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\ril\AppData\Local\Temp\ipykernel_22376\3661106032.py", line 2, in <cell line: 2>
      classifier.fit(x_train,y_train,epochs =1)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\training.py", line 994, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\training.py", line 1052, in compute_loss
      return self.compiled_loss(
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\losses.py", line 152, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\losses.py", line 272, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\ril\anaconda3\lib\site-packages\keras\losses.py", line 2151, in binary_crossentropy
      y_true = tf.cast(y_true, y_pred.dtype)
Node: 'binary_crossentropy/Cast'
Cast string to float is not supported
	 [[{{node binary_crossentropy/Cast}}]] [Op:__inference_train_function_1925]

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
y_pred =(y_pred > 0.5) 

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix( y_test, y_pred)

In [ ]:
new_prediction = classifier.predict(sc.transform(np.array([[   ]])))
new_prediction = (new_prediction > 0.5)

In [43]:
# Evaluating , improving and tuning the ANN

In [ ]:
# k fold validation

In [49]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [50]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(6, kernel_initializer='glorot_uniform', activation ='relu', input_dim = 11)) 
    classifier.add(Dense(6, kernel_initializer='glorot_uniform', activation ='relu')) 
    classifier.add(Dense(1, kernel_initializer='glorot_uniform', activation ='sigmoid', input_dim = 11)) 
    classifier.compile(optimizer ='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

In [55]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, nb_epoch =10)

C:\Users\ril\AppData\Local\Temp\ipykernel_22376\314327845.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs =10)


In [57]:
accuracies = cross_val_score(estimator = classifier, X= x_train, y=y_train, cv= 10, n_jobs =-1 )

In [58]:
mean = accuracies.mean()
variance = accuracies.std()

In [59]:
mean

0.6188749969005585

In [62]:
variance

0.07039498446658465

In [63]:
# adding the input layer and first hidden layer with dropout
from keras.layers import Dropout

In [67]:
classifier.add(Dropout(rate = 0.1))